#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn workspaces run lint
echo "######################"
echo "Successfully compiled Lint"
echo "######################"

yarn workspaces run format
echo "######################"
echo "Successfully compiled format"
echo "######################"

yarn workspaces run test:headless
echo "######################"
echo "Successfully compiled test"
echo "######################"
