#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn run lint
echo "######################"
echo "Successfully compiled Lint"
echo "######################"

yarn run format
echo "######################"
echo "Successfully compiled format"
echo "######################"

yarn run test:headless
echo "######################"
echo "Successfully compiled test"
echo "######################"
